---
title: "lecture_6_walkthrough"
author: "LQ"
date: "5/1/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# (A. Can you improve this analysis?
df <- data.frame(a=1:10, b=seq(200,400,length=10),c=11:20,d=NA)
df$b <- (df$b - min(df$b)) / (max(df$b) - min(df$b))
df$b

df$a <- (df$a - min(df$a)) / (max(df$a) - min(df$a))
df$b <- (df$b - min(df$b)) / (max(df$b) - min(df$b))
df$b
df$c <- (df$c - min(df$c)) / (max(df$c) - min(df$c))
df$d <- (df$d - min(df$d)) / (max(df$d) - min(df$d))

range(df$b)
```


```{r}

## Improvement - walkthrough in class

##Original improvement, simple answer
rescale <- function(x) {
  rng <-range(x)
   (x - rng[1]) / (rng[2] - rng[1])
  } 

rescale(1:10)

##Next improvement with vector to remove NA - does not actually remove NA from the results, but it removes NA from being utilized for the function so it doesn't throw NA's for the entirety of results

rescale2 <- function(x, na.rm = TRUE) {
  rng <-range(x, na.rm = TRUE)
   (x - rng[1]) / (rng[2] - rng[1]) 
  } 

x = c(1,2,3,NA,10)
rescale2(x)

##Testing rescale2 on (c(1,10,"string")) results in an error because "string" is not a numeric input

```



```{r}
## Walkthrough in class

rescale3 <- function(x, na.rm=TRUE, plot=FALSE) {
   if(na.rm) {
     rng <-range(x, na.rm=na.rm)
   } else {
     rng <-range(x)
   }
   print("Hello")
   answer <- (x - rng[1]) / (rng[2] - rng[1])
   print("is it me you are looking for?")
   if(plot) {
      plot(answer, typ="b", lwd=4)
}
   print("I can see it in ...")
}

rescale3(1:10)

```

```{r}
rescale4 <- function(x, na.rm=TRUE, plot=FALSE) {
   if(na.rm) {
     rng <-range(x, na.rm=TRUE)
   } else {
     rng <-range(x)
   }
   print("Hello")
   answer <- (x - rng[1]) / (rng[2] - rng[1])
   return(answer)
   print("is it me you are looking for?")
   if(plot) {
      plot(answer, typ="b", lwd=4)
}
   print("I can see it in ...")
}
rescale4(1:10)

?return(value)
```

```{r}
add <- function(x, y=1) {
# Sum the input x and y 
  x+y
}
add(x=1, y=4)
add(1, 4)
add(1)
add( c(1, 2, 3) )
add( c(1, 2, 3), 4 )
#in class example - meant to throw errors
#add(1, 2, 2)
#add(x=1, y=“b”)
```

```{r}
##Code snippet
library("bio3d")
simp_call <- function(x){
  read.pdb(x)
}

read_x <- simp_call("4AKE")
read_x

simp_trim <- function(read_x){
  trim.pdb(read_x, chain="A", elety="CA")
}

trim_x <- simp_trim(read_x)
trim_x

chainatom_x <- function(trim_x) {
  trim_x$atom$b
}

data_x <- chainatom_x(trim_x)
data_x

plot_x <- function(data_x){
  plotb3(data_x, sse=trim_x, typ="l", ylab="Bfactor")
  return(plot_x)
}

plot_x(data_x)

```





